name: LogLogRevolution
version: '@VERSION@'
main: party.bongs.loglogrevolution.Plugin
api-version: '1.20'
author: bohnentoni
authors: [ nothub ]
description: Wroom Wroom Tree Chop like Ferrarogini
website: https://github.com/bohnentoni/loglogrevolution
